exclude: .*migrations\/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
# - repo: https://github.com/pycqa/flake8
#   rev: 6.0.0
#   hooks:
#     - id: flake8
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: pylint
#       language: system
#       types: [python]
#       args:
#         [
#           "-rn",
#           "-sn",
#           "--load-plugins=pylint_django",
#           "--django-settings-module=testsite.settings",
#           "--ignore=manage.py",
#         ]
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.34.1
  hooks:
    - id: djlint-django
